# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.TextField(choices=[(b'1', b'1 aula'), (b'2', b'2 aulas'), (b'3', b'3 aulas'), (b'4', b'4 aulas'), (b'5', b'5 aulas'), (b'6', b'6 aulas')], max_length=1),
        ),
        migrations.AlterField(
            model_name='professor',
            name='restricao_horario',
            field=models.TextField(choices=[(b'0', b'Nenhuma'), (b'1', b'Primeira'), (b'2', b'Segunda'), (b'3', b'Terceira'), (b'4', b'Quarta'), (b'5', b'Quinta'), (b'6', b'Sexta')], max_length=1),
        ),
    ]
