# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-04 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga_horaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeira', models.CharField(max_length=20)),
                ('segunda', models.CharField(max_length=20)),
                ('terceira', models.CharField(choices=[(b'1', b'1 aula'), (b'2', b'2 aulas'), (b'3', b'3 aulas'), (b'4', b'4 aulas'), (b'5', b'5 aulas'), (b'6', b'6 aulas')], max_length=20)),
            ],
        ),
    ]
