# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_auto_20171203_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='restricao_dia_semana',
            field=models.CharField(choices=[(b'0', b'Nenhuma'), (b'2', b'Segunda'), (b'3', b'Ter\xc3\xa7a'), (b'4', b'Quarta'), (b'5', b'Quinta'), (b'6', b'Sexta')], max_length=5),
        ),
        migrations.AlterField(
            model_name='professor',
            name='restricao_horario',
            field=models.TextField(choices=[(b'0', b'Nenhuma'), (b'1', b'Primeira'), (b'2', b'Segunda'), (b'3', b'Terceira'), (b'4', b'Quarta'), (b'5', b'Quinta'), (b'6', b'Sexta')], max_length=8),
        ),
    ]
